development:
  cloud_name: dbozbczqe
  api_key: '387233612562628'
  api_secret: PkSjfbn_IssMVYlWzLq8WKoYsEU
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dbozbczqe
  api_key: '387233612562628'
  api_secret: PkSjfbn_IssMVYlWzLq8WKoYsEU
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dbozbczqe
  api_key: '387233612562628'
  api_secret: PkSjfbn_IssMVYlWzLq8WKoYsEU
  enhance_image_tag: true
  static_file_support: false